package teacommontea.veritechasse.vanilla.Enchantments.Tags;

import teacommontea.veritechasse.vanilla.Enchantments.Tags.Types.ItemTag;

public final class EnchantableDurability {

    public static final String KEY = "enchantable/durability";

    public static final ItemTag TAG = ItemTag.of(KEY,
        "leather_boots",
        "copper_boots",
        "chainmail_boots",
        "golden_boots",
        "iron_boots",
        "diamond_boots",
        "netherite_boots",
        "leather_leggings",
        "copper_leggings",
        "chainmail_leggings",
        "golden_leggings",
        "iron_leggings",
        "diamond_leggings",
        "netherite_leggings",
        "leather_chestplate",
        "copper_chestplate",
        "chainmail_chestplate",
        "golden_chestplate",
        "iron_chestplate",
        "diamond_chestplate",
        "netherite_chestplate",
        "leather_helmet",
        "copper_helmet",
        "chainmail_helmet",
        "golden_helmet",
        "iron_helmet",
        "diamond_helmet",
        "netherite_helmet",
        "turtle_helmet",
        "elytra",
        "shield",
        "wooden_sword",
        "stone_sword",
        "copper_sword",
        "golden_sword",
        "iron_sword",
        "diamond_sword",
        "netherite_sword",
        "wooden_axe",
        "stone_axe",
        "copper_axe",
        "golden_axe",
        "iron_axe",
        "diamond_axe",
        "netherite_axe",
        "wooden_pickaxe",
        "stone_pickaxe",
        "copper_pickaxe",
        "golden_pickaxe",
        "iron_pickaxe",
        "diamond_pickaxe",
        "netherite_pickaxe",
        "wooden_shovel",
        "stone_shovel",
        "copper_shovel",
        "golden_shovel",
        "iron_shovel",
        "diamond_shovel",
        "netherite_shovel",
        "wooden_hoe",
        "stone_hoe",
        "copper_hoe",
        "golden_hoe",
        "iron_hoe",
        "diamond_hoe",
        "netherite_hoe",
        "wooden_spear",
        "stone_spear",
        "copper_spear",
        "golden_spear",
        "iron_spear",
        "diamond_spear",
        "netherite_spear",
        "bow",
        "crossbow",
        "trident",
        "mace",
        "flint_and_steel",
        "shears",
        "brush",
        "fishing_rod",
        "carrot_on_a_stick",
        "warped_fungus_on_a_stick");

    private EnchantableDurability() {
    }
}
