package teacommontea.veritechasse.Vanilla.PlayerMovement.PlayerServerboundPackets;

import java.util.List;
import java.util.Locale;
import java.util.Map;

import teacommontea.veritechasse.Vanilla.Protocol;

public final class PacketRegistry {

    private static final Map<String, PacketDefinition> BY_NAME = Map.ofEntries(
        Map.entry(PacketNames.ACCEPT_CODE_OF_CONDUCT,
            new PacketDefinition(PacketNames.ACCEPT_CODE_OF_CONDUCT,
                new int[] {1, 21, 9}, null,
                List.of(PacketPhase.CONFIGURATION),
                List.of("ServerboundAcceptCodeOfConductPacket"))),
        Map.entry(PacketNames.ACCEPT_TELEPORTATION,
            new PacketDefinition(PacketNames.ACCEPT_TELEPORTATION,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundAcceptTeleportationPacket"))),
        Map.entry(PacketNames.ATTACK,
            new PacketDefinition(PacketNames.ATTACK,
                new int[] {26, 1, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundAttackPacket"))),
        Map.entry(PacketNames.BLOCK_ENTITY_TAG_QUERY,
            new PacketDefinition(PacketNames.BLOCK_ENTITY_TAG_QUERY,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundBlockEntityTagQuery", "ServerboundBlockEntityTagQueryPacket"))),
        Map.entry(PacketNames.CHANGE_DIFFICULTY,
            new PacketDefinition(PacketNames.CHANGE_DIFFICULTY,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChangeDifficultyPacket"))),
        Map.entry(PacketNames.CHANGE_GAME_MODE,
            new PacketDefinition(PacketNames.CHANGE_GAME_MODE,
                new int[] {1, 21, 6}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChangeGameModePacket"))),
        Map.entry(PacketNames.CHAT,
            new PacketDefinition(PacketNames.CHAT,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChatPacket"))),
        Map.entry(PacketNames.CHAT_ACK,
            new PacketDefinition(PacketNames.CHAT_ACK,
                new int[] {1, 19, 1}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChatAckPacket"))),
        Map.entry(PacketNames.CHAT_COMMAND,
            new PacketDefinition(PacketNames.CHAT_COMMAND,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChatCommandPacket"))),
        Map.entry(PacketNames.CHAT_COMMAND_SIGNED,
            new PacketDefinition(PacketNames.CHAT_COMMAND_SIGNED,
                new int[] {1, 20, 5}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChatCommandSignedPacket"))),
        Map.entry(PacketNames.CHAT_PREVIEW,
            new PacketDefinition(PacketNames.CHAT_PREVIEW,
                new int[] {1, 19, 0}, new int[] {1, 19, 3},
                List.of(PacketPhase.GAME),
                List.of("ServerboundChatPreviewPacket"))),
        Map.entry(PacketNames.CHAT_SESSION_UPDATE,
            new PacketDefinition(PacketNames.CHAT_SESSION_UPDATE,
                new int[] {1, 19, 3}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChatSessionUpdatePacket"))),
        Map.entry(PacketNames.CHUNK_BATCH_RECEIVED,
            new PacketDefinition(PacketNames.CHUNK_BATCH_RECEIVED,
                new int[] {1, 20, 2}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundChunkBatchReceivedPacket"))),
        Map.entry(PacketNames.CLIENT_COMMAND,
            new PacketDefinition(PacketNames.CLIENT_COMMAND,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundClientCommandPacket"))),
        Map.entry(PacketNames.CLIENT_INFORMATION,
            new PacketDefinition(PacketNames.CLIENT_INFORMATION,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.COMMON, PacketPhase.GAME),
                List.of("ServerboundClientInformationPacket"))),
        Map.entry(PacketNames.CLIENT_TICK_END,
            new PacketDefinition(PacketNames.CLIENT_TICK_END,
                new int[] {1, 21, 2}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundClientTickEndPacket"))),
        Map.entry(PacketNames.COMMAND_SUGGESTION,
            new PacketDefinition(PacketNames.COMMAND_SUGGESTION,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundCommandSuggestionPacket"))),
        Map.entry(PacketNames.CONFIGURATION_ACKNOWLEDGED,
            new PacketDefinition(PacketNames.CONFIGURATION_ACKNOWLEDGED,
                new int[] {1, 20, 2}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundConfigurationAcknowledgedPacket"))),
        Map.entry(PacketNames.CONTAINER_BUTTON_CLICK,
            new PacketDefinition(PacketNames.CONTAINER_BUTTON_CLICK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundContainerButtonClickPacket"))),
        Map.entry(PacketNames.CONTAINER_CLICK,
            new PacketDefinition(PacketNames.CONTAINER_CLICK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundContainerClickPacket"))),
        Map.entry(PacketNames.CONTAINER_CLOSE,
            new PacketDefinition(PacketNames.CONTAINER_CLOSE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundContainerClosePacket"))),
        Map.entry(PacketNames.CONTAINER_SLOT_STATE_CHANGED,
            new PacketDefinition(PacketNames.CONTAINER_SLOT_STATE_CHANGED,
                new int[] {1, 20, 3}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundContainerSlotStateChangedPacket"))),
        Map.entry(PacketNames.COOKIE_RESPONSE,
            new PacketDefinition(PacketNames.COOKIE_RESPONSE,
                new int[] {1, 20, 5}, null,
                List.of(PacketPhase.COOKIE),
                List.of("ServerboundCookieResponsePacket"))),
        Map.entry(PacketNames.CUSTOM_CLICK_ACTION,
            new PacketDefinition(PacketNames.CUSTOM_CLICK_ACTION,
                new int[] {1, 21, 6}, null,
                List.of(PacketPhase.COMMON),
                List.of("ServerboundCustomClickActionPacket"))),
        Map.entry(PacketNames.CUSTOM_PAYLOAD,
            new PacketDefinition(PacketNames.CUSTOM_PAYLOAD,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.COMMON, PacketPhase.GAME),
                List.of("ServerboundCustomPayloadPacket"))),
        Map.entry(PacketNames.CUSTOM_QUERY_ANSWER,
            new PacketDefinition(PacketNames.CUSTOM_QUERY_ANSWER,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.LOGIN),
                List.of("ServerboundCustomQueryAnswerPacket", "ServerboundCustomQueryPacket"))),
        Map.entry(PacketNames.DEBUG_SUBSCRIPTION_REQUEST,
            new PacketDefinition(PacketNames.DEBUG_SUBSCRIPTION_REQUEST,
                new int[] {1, 20, 5}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundDebugSampleSubscriptionPacket", "ServerboundDebugSubscriptionRequestPacket"))),
        Map.entry(PacketNames.EDIT_BOOK,
            new PacketDefinition(PacketNames.EDIT_BOOK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundEditBookPacket"))),
        Map.entry(PacketNames.ENTITY_TAG_QUERY,
            new PacketDefinition(PacketNames.ENTITY_TAG_QUERY,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundEntityTagQuery", "ServerboundEntityTagQueryPacket"))),
        Map.entry(PacketNames.FINISH_CONFIGURATION,
            new PacketDefinition(PacketNames.FINISH_CONFIGURATION,
                new int[] {1, 20, 2}, null,
                List.of(PacketPhase.CONFIGURATION),
                List.of("ServerboundFinishConfigurationPacket"))),
        Map.entry(PacketNames.HELLO,
            new PacketDefinition(PacketNames.HELLO,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.LOGIN),
                List.of("ServerboundHelloPacket"))),
        Map.entry(PacketNames.INTERACT,
            new PacketDefinition(PacketNames.INTERACT,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundInteractPacket"))),
        Map.entry(PacketNames.JIGSAW_GENERATE,
            new PacketDefinition(PacketNames.JIGSAW_GENERATE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundJigsawGeneratePacket"))),
        Map.entry(PacketNames.KEEP_ALIVE,
            new PacketDefinition(PacketNames.KEEP_ALIVE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.COMMON, PacketPhase.GAME),
                List.of("ServerboundKeepAlivePacket"))),
        Map.entry(PacketNames.KEY,
            new PacketDefinition(PacketNames.KEY,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.LOGIN),
                List.of("ServerboundKeyPacket"))),
        Map.entry(PacketNames.LOCK_DIFFICULTY,
            new PacketDefinition(PacketNames.LOCK_DIFFICULTY,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundLockDifficultyPacket"))),
        Map.entry(PacketNames.LOGIN_ACKNOWLEDGED,
            new PacketDefinition(PacketNames.LOGIN_ACKNOWLEDGED,
                new int[] {1, 20, 2}, null,
                List.of(PacketPhase.LOGIN),
                List.of("ServerboundLoginAcknowledgedPacket"))),
        Map.entry(PacketNames.MOVE_PLAYER,
            new PacketDefinition(PacketNames.MOVE_PLAYER,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundMovePlayerPacket"))),
        Map.entry(PacketNames.MOVE_VEHICLE,
            new PacketDefinition(PacketNames.MOVE_VEHICLE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundMoveVehiclePacket"))),
        Map.entry(PacketNames.PADDLE_BOAT,
            new PacketDefinition(PacketNames.PADDLE_BOAT,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPaddleBoatPacket"))),
        Map.entry(PacketNames.PICK_ITEM,
            new PacketDefinition(PacketNames.PICK_ITEM,
                new int[] {1, 19, 0}, new int[] {1, 21, 4},
                List.of(PacketPhase.GAME),
                List.of("ServerboundPickItemPacket"))),
        Map.entry(PacketNames.PICK_ITEM_FROM_BLOCK,
            new PacketDefinition(PacketNames.PICK_ITEM_FROM_BLOCK,
                new int[] {1, 21, 4}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPickItemFromBlockPacket"))),
        Map.entry(PacketNames.PICK_ITEM_FROM_ENTITY,
            new PacketDefinition(PacketNames.PICK_ITEM_FROM_ENTITY,
                new int[] {1, 21, 4}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPickItemFromEntityPacket"))),
        Map.entry(PacketNames.PING_REQUEST,
            new PacketDefinition(PacketNames.PING_REQUEST,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.PING, PacketPhase.STATUS),
                List.of("ServerboundPingRequestPacket"))),
        Map.entry(PacketNames.PLACE_RECIPE,
            new PacketDefinition(PacketNames.PLACE_RECIPE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPlaceRecipePacket"))),
        Map.entry(PacketNames.PLAYER_ABILITIES,
            new PacketDefinition(PacketNames.PLAYER_ABILITIES,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPlayerAbilitiesPacket"))),
        Map.entry(PacketNames.PLAYER_ACTION,
            new PacketDefinition(PacketNames.PLAYER_ACTION,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPlayerActionPacket"))),
        Map.entry(PacketNames.PLAYER_COMMAND,
            new PacketDefinition(PacketNames.PLAYER_COMMAND,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPlayerCommandPacket"))),
        Map.entry(PacketNames.PLAYER_INPUT,
            new PacketDefinition(PacketNames.PLAYER_INPUT,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPlayerInputPacket"))),
        Map.entry(PacketNames.PLAYER_LOADED,
            new PacketDefinition(PacketNames.PLAYER_LOADED,
                new int[] {1, 21, 4}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundPlayerLoadedPacket"))),
        Map.entry(PacketNames.PONG,
            new PacketDefinition(PacketNames.PONG,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.COMMON, PacketPhase.GAME),
                List.of("ServerboundPongPacket"))),
        Map.entry(PacketNames.RECIPE_BOOK_CHANGE_SETTINGS,
            new PacketDefinition(PacketNames.RECIPE_BOOK_CHANGE_SETTINGS,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundRecipeBookChangeSettingsPacket"))),
        Map.entry(PacketNames.RECIPE_BOOK_SEEN_RECIPE,
            new PacketDefinition(PacketNames.RECIPE_BOOK_SEEN_RECIPE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundRecipeBookSeenRecipePacket"))),
        Map.entry(PacketNames.RENAME_ITEM,
            new PacketDefinition(PacketNames.RENAME_ITEM,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundRenameItemPacket"))),
        Map.entry(PacketNames.RESOURCE_PACK,
            new PacketDefinition(PacketNames.RESOURCE_PACK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.COMMON, PacketPhase.GAME),
                List.of("ServerboundResourcePackPacket"))),
        Map.entry(PacketNames.SEEN_ADVANCEMENTS,
            new PacketDefinition(PacketNames.SEEN_ADVANCEMENTS,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSeenAdvancementsPacket"))),
        Map.entry(PacketNames.SELECT_BUNDLE_ITEM,
            new PacketDefinition(PacketNames.SELECT_BUNDLE_ITEM,
                new int[] {1, 21, 2}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSelectBundleItemPacket"))),
        Map.entry(PacketNames.SELECT_KNOWN_PACKS,
            new PacketDefinition(PacketNames.SELECT_KNOWN_PACKS,
                new int[] {1, 20, 5}, null,
                List.of(PacketPhase.CONFIGURATION),
                List.of("ServerboundSelectKnownPacks"))),
        Map.entry(PacketNames.SELECT_TRADE,
            new PacketDefinition(PacketNames.SELECT_TRADE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSelectTradePacket"))),
        Map.entry(PacketNames.SET_BEACON,
            new PacketDefinition(PacketNames.SET_BEACON,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetBeaconPacket"))),
        Map.entry(PacketNames.SET_CARRIED_ITEM,
            new PacketDefinition(PacketNames.SET_CARRIED_ITEM,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetCarriedItemPacket"))),
        Map.entry(PacketNames.SET_COMMAND_BLOCK,
            new PacketDefinition(PacketNames.SET_COMMAND_BLOCK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetCommandBlockPacket"))),
        Map.entry(PacketNames.SET_COMMAND_MINECART,
            new PacketDefinition(PacketNames.SET_COMMAND_MINECART,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetCommandMinecartPacket"))),
        Map.entry(PacketNames.SET_CREATIVE_MODE_SLOT,
            new PacketDefinition(PacketNames.SET_CREATIVE_MODE_SLOT,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetCreativeModeSlotPacket"))),
        Map.entry(PacketNames.SET_GAME_RULE,
            new PacketDefinition(PacketNames.SET_GAME_RULE,
                new int[] {26, 1, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetGameRulePacket"))),
        Map.entry(PacketNames.SET_JIGSAW_BLOCK,
            new PacketDefinition(PacketNames.SET_JIGSAW_BLOCK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetJigsawBlockPacket"))),
        Map.entry(PacketNames.SET_STRUCTURE_BLOCK,
            new PacketDefinition(PacketNames.SET_STRUCTURE_BLOCK,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetStructureBlockPacket"))),
        Map.entry(PacketNames.SET_TEST_BLOCK,
            new PacketDefinition(PacketNames.SET_TEST_BLOCK,
                new int[] {1, 21, 5}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSetTestBlockPacket"))),
        Map.entry(PacketNames.SIGN_UPDATE,
            new PacketDefinition(PacketNames.SIGN_UPDATE,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSignUpdatePacket"))),
        Map.entry(PacketNames.SPECTATOR_ACTION,
            new PacketDefinition(PacketNames.SPECTATOR_ACTION,
                new int[] {26, 1, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSpectateEntityPacket", "ServerboundSpectatorActionPacket"))),
        Map.entry(PacketNames.STATUS_REQUEST,
            new PacketDefinition(PacketNames.STATUS_REQUEST,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.STATUS),
                List.of("ServerboundStatusRequestPacket"))),
        Map.entry(PacketNames.SWING,
            new PacketDefinition(PacketNames.SWING,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundSwingPacket"))),
        Map.entry(PacketNames.TELEPORT_TO_ENTITY,
            new PacketDefinition(PacketNames.TELEPORT_TO_ENTITY,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundTeleportToEntityPacket"))),
        Map.entry(PacketNames.TEST_INSTANCE_BLOCK_ACTION,
            new PacketDefinition(PacketNames.TEST_INSTANCE_BLOCK_ACTION,
                new int[] {1, 21, 5}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundTestInstanceBlockActionPacket"))),
        Map.entry(PacketNames.USE_ITEM,
            new PacketDefinition(PacketNames.USE_ITEM,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundUseItemPacket"))),
        Map.entry(PacketNames.USE_ITEM_ON,
            new PacketDefinition(PacketNames.USE_ITEM_ON,
                new int[] {1, 19, 0}, null,
                List.of(PacketPhase.GAME),
                List.of("ServerboundUseItemOnPacket")))
    );

    private PacketRegistry() {
    }

    public static String normalise(String name) {
        if (name == null) {
            return null;
        }
        String trimmed = name.trim();
        if (trimmed.isEmpty()) {
            return null;
        }
        if (trimmed.indexOf('.') >= 0 || trimmed.startsWith("Serverbound")) {
            return stableNameOf(trimmed);
        }
        return trimmed.toLowerCase(Locale.ROOT);
    }

    public static PacketDefinition definitionOf(String stableName) {
        if (stableName == null) {
            return null;
        }
        return BY_NAME.get(stableName.toLowerCase(Locale.ROOT));
    }

    public static boolean exists(String stableName, Protocol protocol) {
        PacketDefinition definition = definitionOf(stableName);
        return definition != null && definition.existsIn(protocol);
    }

    public static PacketDefinition byClassName(String className) {
        if (className == null) {
            return null;
        }
        for (PacketDefinition definition : BY_NAME.values()) {
            if (definition.matchesClass(className)) {
                return definition;
            }
        }
        return null;
    }

    public static String stableNameOf(String className) {
        PacketDefinition definition = byClassName(className);
        return definition == null ? null : definition.stableName();
    }

    public static int count() {
        return BY_NAME.size();
    }

    public static java.util.Set<String> names() {
        return BY_NAME.keySet();
    }
}
